# Generated by Django 5.2.17 on 2026-08-24 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_tin', models.CharField(db_index=True, max_length=50, unique=True)),
                ('clinic_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('branch_name', models.CharField(default='Main', max_length=255)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('setup_fee_etb', models.PositiveIntegerField(default=15000)),
                ('quarterly_fee_etb', models.PositiveIntegerField(default=5000)),
                ('payment_channel', models.CharField(blank=True, default='', max_length=64)),
                ('payment_transaction_ref', models.CharField(blank=True, default='', max_length=128)),
                ('setup_fee_approved', models.BooleanField(default=False)),
                ('subscription_payment_approved', models.BooleanField(default=False)),
                ('subscription_paid_until', models.DateTimeField(blank=True, null=True)),
                ('paid_quarters_count', models.PositiveIntegerField(default=0)),
                ('billing_hold', models.BooleanField(default=False)),
                ('billing_started_at', models.DateTimeField(blank=True, null=True)),
                ('free_trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_illustration', models.BooleanField(default=False)),
                ('billing_notes', models.TextField(blank=True, default='')),
                ('fees_manually_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_tin', models.CharField(db_index=True, max_length=50)),
                ('payment_kind', models.CharField(choices=[('setup', 'Setup'), ('quarterly', 'Quarterly')], db_index=True, max_length=20)),
                ('amount_etb', models.PositiveIntegerField()),
                ('payment_channel', models.CharField(max_length=64)),
                ('transaction_ref', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('quarter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_submissions', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payment_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['clinic_tin', 'payment_kind', 'status'], name='tenants_ten_clinic__d4b8a1_idx')],
            },
        ),
    ]
