# Generated by Django 5.2.17 on 2026-08-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_sales_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantaccount',
            name='ops_mode',
            field=models.CharField(choices=[('online', 'Online (cloud)'), ('offline', 'Offline with evening sync')], db_index=True, default='online', max_length=20),
        ),
    ]
