# Generated by Django 5.2.13 on 2026-08-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantopsmodechangerequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantopsmodechangerequest',
            new_name='tenants_ten_clinic__a8843e_idx',
            old_name='tenants_ops_clinic__a8f2c1_idx',
        ),
    ]
