# Generated by Django 5.2.17 on 2026-08-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_rename_tenants_ops_clinic__a8f2c1_idx_tenants_ten_clinic__a8843e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(db_index=True, max_length=64)),
                ('modules_key', models.CharField(db_index=True, max_length=255)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('setup_fee_etb', models.PositiveIntegerField(default=15000)),
                ('quarterly_fee_etb', models.PositiveIntegerField(default=5000)),
                ('yearly_fee_etb', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_subscriptionpricingrule',
                'ordering': ['sort_order', 'business_type', 'modules_key'],
                'managed': False,
            },
        ),
    ]
