# Generated by Django 5.2.17 on 2026-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_subscriptionpricingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_side', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('sender_username', models.CharField(blank=True, default='', max_length=150)),
                ('read_by_tenant', models.BooleanField(default=False)),
                ('read_by_apex', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tenants_tenantfeedbackmessage',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantFeedbackThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_tin', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(db_index=True, default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants_tenantfeedbackthread',
                'ordering': ['-updated_at'],
                'managed': False,
            },
        ),
    ]
