# Generated by Django 5.2.17 on 2026-08-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch_name',
            field=models.CharField(default='Main', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='clinic_tin',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('reception', 'Reception'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab', 'Lab'), ('pharmacist', 'Pharmacist')], default='manager', max_length=32),
        ),
    ]
