# Generated by Django 5.2.13 on 2026-08-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billableservice',
            name='department',
            field=models.CharField(max_length=120),
        ),
    ]
